name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          bundle install
          bundle exec pod install

      - name: Build and test
        run: |
          xcodebuild clean test \
            -workspace DiamondDeskERP.xcworkspace \
            -scheme DiamondDeskERP \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -enableCodeCoverage YES
        working-directory: .
